name: Run Promotors Script

on:
  schedule:
    # Run every day at 10 PM IST, Monday to Friday
    - cron: '30 16 * * 1-5'  # 4:30 PM UTC = 10:00 PM IST, Mon-Fri
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}  # Ensure this matches the GitHub secret
          SHEET_ID: ${{ secrets.SHEET_ID }}  # Set the Sheet ID as a GitHub secret
        run: python event.py  # Ensure the script path is correct

      - name: Commit and push CSV files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Check and commit CSV files
          if [ -n "$(git status --porcelain *.csv)" ]; then
            git add *.csv
            git commit -m "Add/update CSV files"
            git push
          else
            echo "No CSV files to commit."
